In [29]:
import pandas as pd
import glob
import numpy as np

In [5]:
x = {}
for i in glob.glob("*csv"):
    x[i.split(".")[0]] = pd.read_csv(i)

In [32]:
for i in x.keys():
    print(i)
    print(np.mean( x[i].iloc[:, 3] ))
    print((x[i].iloc[0:3, 0:3].values+x[i].iloc[3:6, 0:3].values+x[i].iloc[6:9, 0:3].values+x[i].iloc[9:12, 0:3].values+x[i].iloc[12:15, 0:3].values)/5)
    print("")

resnet18_ftn_dataaugumented
0.7830508474576272
[[14.6  2.4  2.8]
 [ 3.8 17.6  0.2]
 [ 2.6  1.  14. ]]

resnet18_ftn_nodataaugument
0.7152542372881354
[[12.6  4.4  2.8]
 [ 4.6 15.8  0.4]
 [ 3.8  0.8 13.8]]

resnet18_tfl_dataaugumented
0.7084745762711864
[[12.6  2.4  4. ]
 [ 5.4 17.2  1. ]
 [ 3.   1.4 12. ]]

resnet18_tfl_nodataaugument
0.7118644067796611
[[13.4  3.   4.4]
 [ 6.8 17.6  1.6]
 [ 0.8  0.4 11. ]]

vgg16_ftn_dataaugumented
0.4610169491525424
[[ 8.8  5.6  4.6]
 [11.4 15.4  9.4]
 [ 0.8  0.   3. ]]

vgg16_ftn_nodataaugument
0.39661016949152544
[[ 7.4  5.   4.2]
 [13.6 16.  12.8]
 [ 0.   0.   0. ]]

vgg16_tfl_dataaugumented
0.776271186440678
[[14.2  1.8  3.2]
 [ 4.6 18.   0.2]
 [ 2.2  1.2 13.6]]

vgg16_tfl_nodataaugument
0.759322033898305
[[13.   1.6  2.4]
 [ 7.4 18.6  1.4]
 [ 0.6  0.8 13.2]]

